# Generated by Django 4.1.6 on 2023-02-21 10:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_alter_post_upload_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='upload_time',
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
