# Generated by Django 4.1.6 on 2023-03-01 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0013_like'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user_id', 'post_id')},
        ),
    ]
