# Generated by Django 4.1.6 on 2023-03-01 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0016_alter_comment_unique_together_post_comment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='instagram.comment'),
        ),
    ]
