# Generated by Django 4.1.6 on 2023-03-01 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0017_alter_post_comment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comment_post', to='instagram.user'),
            preserve_default=False,
        ),
    ]
