# Generated by Django 4.1.6 on 2023-03-15 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0019_remove_comment_post_id_remove_comment_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comment_post', to='instagram.post'),
            preserve_default=False,
        ),
    ]
