# Generated by Django 4.1.6 on 2023-03-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0021_comment_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pro_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
