# Generated by Django 4.1.6 on 2023-03-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0022_user_pro_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='caption',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='fullName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
