# Generated by Django 4.1.6 on 2023-03-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0023_user_caption_user_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='caption',
            field=models.TextField(blank=True, default=''),
        ),
    ]
